# Generated by Django 5.0.12 on 2025-03-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Preparing', 'Preparing'), ('Ready to Collect', 'Ready to Collect'), ('Collected', 'Collected')], default='Pending', max_length=20),
        ),
    ]
